name: Daily Commits

on:
  schedule:
    - cron: '15 06 * * *'  # Runs every day at 12:15 UTC
    - cron: '21 06 * * *' 
    - cron: '27 06 * * *' 
    - cron: '33 06 * * *' 
    - cron: '39 06 * * *'  
  workflow_dispatch:       # Allows manual trigger in the GitHub UI

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # ensures full history is available

      - name: Checkout main branch explicitly
        run: git checkout -B main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run commit script
        run: python commit.py

      - name: Configure Git
        run: |
          git config user.name "Tom Richardson"
          git config user.email "tom.richardson824@gmail.com"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Automated commit by bot" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
