name: Daily Commits

on:
  schedule:
    - cron: '15 12 * * *'  # Runs every day at 12:15 UTC
  workflow_dispatch:       # Allows manual trigger in the GitHub UI

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run commit script
        run: python commit.py

      - name: Push changes
        run: |
          git config user.name "Tom Richardson"
          git config user.email "your-email@example.com"
          git push
